name: Build/Test

on:
  push:
    branches:
      - 'develop'
      - 'feature'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependancies
      run: dotnet restore
    - name: Build app
      run: dotnet build --no-restore
    - name: Tests exec
      run: dotnet test --no-build --verbosity normal
